### ISSUE TITLE
Can I use any other method to generate 128 features?

### ISSUE THREAD

**Issue by K0307** [nwojke/deep_sort#6] opened 2017-04-12 06:32 UTC

**Comment by nwojke** [comment] 2017-04-13 11:59
Sure, just replace the last 128 columns in the detection `.npy` file. Also, the code is not actually restricted to 128 dimensions, so you can change the dimensionality of the appearance descriptor by writing less columns to the detection file.

**Comment by WesleyZhang1991** [comment] 2017-04-16 09:55
Hi, I train a similar network with mars 1261 dataset in mxnet. However, the result is not as good for ID switches which means the feature extractor is not as good. I have several questions.
I find that there is a background class in mars dataset and the number of each class is unbalanced. Do you consider the background as a class? Also Is there any data balance?
When considering data augmentation, I notice that color manipulation is used. Do you also introduce random crop?
What is your evaluation metric for the feature extractor? The person reid metric or tracking performance?
Thanks

**Comment by nwojke** [comment] 2017-04-16 12:36
We haven't experimented with class balancing and in our final experiments we did not use the additional distractors. With respect to data augmentation: We don't do crops, but it would probably help. Our evaluation criteria during training was re-id performance

**Comment by Ravisik** [comment] 2017-06-06 14:29
Hi! 

Thanks for this beautiful project. I'm currently working on a realtime implementation for tracking, using py-faster-rcnn and deep sort. However, one method uses Caffe and the other tensorflow, which leads to incompatibility.

Do you know if there a good feature exctractor implemented in caffe or could you explain how to train my own model in caffe?

Thanks a lot :)
Flo

**Comment by harshmunshi** [comment] 2017-06-13 10:02
Ravisik:

https://github.com/smallcorgi/Faster-RCNN_TF

But you don't need that: You can have the output of the faster-rcnn as the MOTA challange format. It works, I've tried.

Hope it helps;;

**Comment by Ravisik** [comment] 2017-06-13 14:13
Hey! Thanks for your response! 

Actually I uses other detectors with caffe, it's why I don't want to convert everything in tensorflow.

What do you mean by "You can have the output of the faster-rcnn as the MOTA challange format."? Faster-rcnn output is a score and a ROI boxe, there are no metric feature, isn't it?

Thanks a lot,
Flo

**Comment by harshmunshi** [comment] 2017-06-13 16:11
Mota format : <frame>, <id>, <bb_left>, <bb_top>, <bb_width>, <bb_height>, <conf>, <x>, <y>, <z>

you can find the details here: https://motchallenge.net/instructions/

so pack your output in this format, change the demo.py file into classes and make objects in a linker python script which can call faster-rcnn code and parse it into deep-sort.

Hope that helps :+1:

**Comment by Ravisik** [comment] 2017-06-13 16:18
Thansks! 

But what is used in deep sort in addition of the Mota format is 128 features ("Deep Association Metric") that allow the tracker to associate each track at each frame. If wee don't use this 128 features the tracker is simply SORT and not Deep SORT!

I don't think that py-faster-rcnn can give us this kind of features directly! It is why I was asking if there was an other way to get these features without tensorflow

**Comment by harshmunshi** [comment] 2017-06-13 16:24
Ahh okay!

This paper might help you: https://www.cs.bu.edu/groups/ivc/software/TrackerHierarchy/AVSS2012_TrackerHierarchy.pdf

It's an old one but the code is open source; use faster-rcnn for detection, in that detected region find and store it's color information to make a stronger vector. Alternate between Kalman and meanshift :)

Hope that helps :+1:

**Comment by Ravisik** [comment] 2017-06-13 16:25
Thanks a lot :)

**Comment by Ravisik** [comment] 2017-06-14 23:01
I did some research. But in order to go further, do you think that replacing features vector of Deep sort by other features vector (in order to don't use TF and to speed up the algorithm) should work? 

I couldn't see if the feature vector of deep sort is calibrate especially for the tracker.  

Thanks a lot!

**Comment by nwojke** [comment] 2017-06-14 23:52
Sorry for the late reply. @harshmunshi thanks for trying to help out here. @Ravisik Of course, you can re-generate features from faster-rcnn bounding boxes using script [generate_detections.py](https://github.com/nwojke/deep_sort/blob/master/generate_detections.py), but if I understand you correctly you are trying to implement a single application that runs py-faster-rcnn detections and deep_sort. In this setup, you run into an incompability between caffe and tensorflow.

Not sure if this works, but the first thing I would try is [multiprocessing](https://docs.python.org/2/library/multiprocessing.html). Maybe, spawning py-faster-rcnn and deep_sort in separate processes solves the problem? It comes at a little overhead and I haven't tried it, though.

About features: deep_sort relies on good appearance descriptors in general, but the network that we use to generate these features has been trained independently in a person re-identification setting. We haven't done any specific calibration to the tracking task. It is _only_ the network architecture that was designed to be fast enough to be applied in a tracking scenario.

If multiprocessing doesn't work and you need to rely on caffe for appearance descriptor computation, a quick solution to your problem might be the following: Swap the provided appearance descriptor by [dgd_person_reid](https://github.com/Cysu/dgd_person_reid). This is a re-identification network that is a bit slower than ours, but it is implemented in caffe.

I hope this helps.

**Comment by Ravisik** [comment] 2017-06-15 00:38
Hello!

Thanks a lot for your response. 
Indeed my goal is to run faster-rcnn and deep sort in the same program, with a problem using caffe and tensorflow. 

One solution is to use py-faster-rcnn with a tensorflow implementation. However, because I use mainly caffe for other detections I will use this solution in last resort. 

I will try multiprocessing and try to find a way to run caffe and tensorflow, if I find a solution I will keep you in touch. If you are interested I can send you a version that combine faster-rcnn and deep sort if it works.

I will try to use dgd_person_reid too, I will tell you whats going on. Again I can send you a version in case of it's work!

Thanks a lot! 
Flo

**Comment by nwojke** [comment] 2017-07-19 10:40
In case you run out of GPU memory when using tensorflow and caffe in parallel,  [this](https://stackoverflow.com/questions/34199233/how-to-prevent-tensorflow-from-allocating-the-totality-of-a-gpu-memory) might also be relevant to you.

**Comment by nwojke** [comment] 2017-07-24 08:07
Closing this, since the original question has been answered.

**Closed by nwojke** 2017-07-24 08:07 UTC

**Comment by JpHu2017** [comment] 2018-07-18 11:52
@Ravisik hello,bro. Have you finished the problem that combine faster-rcnn and deep sort?

**Comment by anzy0621** [comment] 2019-07-12 03:08
@Ravisik @harshmunshi @nwojke can someone help me understand/ point me in the right direction to get the tensorflow implementation of faster rcnn detector + deep sort together in the same program???
